application: rtcbookreader
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /html
  static_dir: html

- url: /images
  static_dir: images 

- url: /js
  static_dir: js

- url: /assets
  static_dir: assets

- url: .*
  script: main.app
  secure: always

inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest
